on:
  push:
    branches:
      - main
  pull_request:

name: Tests

jobs:
  test-linux:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os:
    #       - ubuntu-latest
    #       - windows-latest
    #       - macOS-latest
    steps:
     - name: Checkout sources
       uses: actions/checkout@v4

     - name: Run tests
       run: |
         cargo install cargo-vcpkg
         cargo vcpkg build
         export VCPKG_ROOT="${CARGO_TARGET_DIR:-$(pwd)/target}/vcpkg"
         export TECTONIC_DEP_BACKEND=vcpkg
         cargo test 
  test-windows:
    runs-on: windows-2019
    steps:
     - name: Checkout sources
       uses: actions/checkout@v4

     - name: Run tests
       run: |
         cargo install cargo-vcpkg
         cargo vcpkg build
         set VCPKG_ROOT="${CARGO_TARGET_DIR:-$(pwd)/target}/vcpkg"
         set RUSTFLAGS='-Ctarget-feature=+crt-static'
         set VCPKGRS_TRIPLET='x64-windows-static-release'
         set TECTONIC_DEP_BACKEND=vcpkg
         cargo test 
